### ISSUE TITLE
Rails 7 credentials

### ISSUE THREAD

**Issue by skliask** [uploadcare/uploadcare-rails#109]
### Issues with rails 7

Thanks for the good job!
 
While the point i will raise is not creating a current problem, it might create problems in the near future. 
The issue is that it would be nice if the keys would be loaded through rails credentials instead of needing to work with .env files. It would be closer to "The Rails way"

**Comment by kraft001** [comment]
With the new version 4.3.1 of `uploadcare-ruby`  it's possible to use keys from Rails credentials. For example:

``` YAML
### config/credentials.yml

uploadcare:
  public_key: my_public_key
  secret_key: my_secret_key
```

``` Ruby
### config/initializers/uploadcare.rb

Uploadcare::Rails.configure do |config|
  config.public_key = Rails.application.credentials.dig(:uploadcare, :public_key)
  config.secret_key = Rails.application.credentials.dig(:uploadcare, :secret_key)
end
```
