### ISSUE TITLE
Allow use of ENV variables for public/private keys

### ISSUE THREAD

**Issue by fulstop** [uploadcare/uploadcare-rails#82]
I'd like to store these values in environment variables instead of checking them into the repository. Is this possible with an alternative configuration method?

**Comment by dmitry-mukhin** [comment]
what do you mean by blows up?

**Comment by fulstop** [comment]
``` sh
Private or public key options were not provided (ArgumentError)
```

I was able to get this working by providing a fallback string in `config/uploadcare.yml`. ENV vars load successfully, and it prevents the exception during initialization.

```yml
defaults: &defaults                                                              
  public_key: <%= ENV["UPLOADCARE_PUBLIC_KEY"] || 'asdf' %>                                
  private_key: <%= ENV["UPLOADCARE_PRIVATE_KEY"] || 'asdf' %>
```
